// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZ35aug-9LVSmZV4bO2ojPyrKhkAT_Xo',
    appId: '1:486374809682:web:32d2d71b3c8c6b0507bf8b',
    messagingSenderId: '486374809682',
    projectId: 'ict602-flutter-app',
    authDomain: 'ict602-flutter-app.firebaseapp.com',
    storageBucket: 'ict602-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwukAS2CO_GN-_Fza5hwPKvZZmDSaikz8',
    appId: '1:486374809682:android:8d9b582148dae18607bf8b',
    messagingSenderId: '486374809682',
    projectId: 'ict602-flutter-app',
    storageBucket: 'ict602-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUeOICIwximmr5yE52Ma3bsgreHPQbgyY',
    appId: '1:486374809682:ios:2874f5d984d5ba2e07bf8b',
    messagingSenderId: '486374809682',
    projectId: 'ict602-flutter-app',
    storageBucket: 'ict602-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.ict602App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUeOICIwximmr5yE52Ma3bsgreHPQbgyY',
    appId: '1:486374809682:ios:2874f5d984d5ba2e07bf8b',
    messagingSenderId: '486374809682',
    projectId: 'ict602-flutter-app',
    storageBucket: 'ict602-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.ict602App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnZ35aug-9LVSmZV4bO2ojPyrKhkAT_Xo',
    appId: '1:486374809682:web:7024a41e163288c107bf8b',
    messagingSenderId: '486374809682',
    projectId: 'ict602-flutter-app',
    authDomain: 'ict602-flutter-app.firebaseapp.com',
    storageBucket: 'ict602-flutter-app.firebasestorage.app',
  );

}