// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8YhNGcQnZlj7VGICcoLB5G-Cg_WiyZj0',
    appId: '1:317237958726:web:20745f5bf73d112c3c9247',
    messagingSenderId: '317237958726',
    projectId: 'carry-mark-ict602',
    authDomain: 'carry-mark-ict602.firebaseapp.com',
    storageBucket: 'carry-mark-ict602.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8YhNGcQnZlj7VGICcoLB5G-Cg_WiyZj0',
    appId: '1:317237958726:android:20745f5bf73d112c3c9247',
    messagingSenderId: '317237958726',
    projectId: 'carry-mark-ict602',
    storageBucket: 'carry-mark-ict602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8YhNGcQnZlj7VGICcoLB5G-Cg_WiyZj0',
    appId: '1:317237958726:ios:20745f5bf73d112c3c9247',
    messagingSenderId: '317237958726',
    projectId: 'carry-mark-ict602',
    storageBucket: 'carry-mark-ict602.firebasestorage.app',
    iosBundleId: 'com.example.carryMarkApp',
  );
}
