// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtpnlliHKHqZWh4eEfj8hYVY-qZJsUkD8',
    appId: '1:252492248210:web:e859ef5d013d783357624b',
    messagingSenderId: '252492248210',
    projectId: 'ict602-8865e',
    authDomain: 'ict602-8865e.firebaseapp.com',
    storageBucket: 'ict602-8865e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtKTVU1djrEy6X_foJl60stRkVZlBSSFQ',
    appId: '1:252492248210:android:2aaa74b5f806f60a57624b',
    messagingSenderId: '252492248210',
    projectId: 'ict602-8865e',
    storageBucket: 'ict602-8865e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNM8ukjQ43Osxsqn4_30yLVafps-9HBm8',
    appId: '1:252492248210:ios:e222b4052353946757624b',
    messagingSenderId: '252492248210',
    projectId: 'ict602-8865e',
    storageBucket: 'ict602-8865e.firebasestorage.app',
    iosBundleId: 'com.example.ict602',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNM8ukjQ43Osxsqn4_30yLVafps-9HBm8',
    appId: '1:252492248210:ios:e222b4052353946757624b',
    messagingSenderId: '252492248210',
    projectId: 'ict602-8865e',
    storageBucket: 'ict602-8865e.firebasestorage.app',
    iosBundleId: 'com.example.ict602',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtpnlliHKHqZWh4eEfj8hYVY-qZJsUkD8',
    appId: '1:252492248210:web:8aacc351df179b2257624b',
    messagingSenderId: '252492248210',
    projectId: 'ict602-8865e',
    authDomain: 'ict602-8865e.firebaseapp.com',
    storageBucket: 'ict602-8865e.firebasestorage.app',
  );

}